#!/usr/bin/env bash
# Inject tenant (white-label) env: copies tenants/<id>/ into root .env.local
# Usage: ./scripts/inject_tenant_config.sh <tenant>
# Writes .hillcode-tenant and root .env.local (VITE_* for theming and APIs).
set -e

TENANT="${1:-default}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TENANT_DIR="$ROOT/tenants/$TENANT"

if [ ! -d "$TENANT_DIR" ]; then
  echo "Unknown tenant: $TENANT" >&2
  exit 1
fi

# Prefer, in order: .env.local, env, .env
if [ -f "$TENANT_DIR/.env.local" ]; then
  cp "$TENANT_DIR/.env.local" "$ROOT/.env.local"
elif [ -f "$TENANT_DIR/env" ]; then
  cp "$TENANT_DIR/env" "$ROOT/.env.local"
elif [ -f "$TENANT_DIR/.env" ]; then
  cp "$TENANT_DIR/.env" "$ROOT/.env.local"
else
  # Minimal: tenant id for import.meta.env.VITE_TENANT
  cat > "$ROOT/.env.local" << EOF
# Generated by inject_tenant_config.sh (add tenants/${TENANT}/env to version control)
VITE_TENANT=${TENANT}
EOF
fi

printf '%s' "$TENANT" > "$ROOT/.hillcode-tenant"
echo "Injected tenant: $TENANT"
